[package]
name = "scram-rs"
version = "0.4.4"
authors = ["Aleksandr Morozov <alex@nixd.org>"]
edition = "2021"
description="Salted Challenge Response Authentication Mechanism (SCRAM) SASL mechanism, a library which implements SCRAM logic"
repository = "https://gitlab.com/relkom/scram-rs"
keywords = ["SCRAM", "SASL"]
categories = ["authentication", "network-programming"]
license="MPL-2.0"

# Since v 0.4.2 this project is relicensed with MPLv2.0.
# The contributors and authors agreed to change license:
# Aleksandr Morozov
# RELKOM s.r.o

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
overflow-checks = true
lto = true

[features]
default = ["use_default"]
use_default = []
use_ring = []

[dependencies]

#non GPL
getrandom="0.2"
base64 = "0.13"
md-5 = "0.10"
sha-1 = "0.10"
sha2 = "0.10"
hmac = "0.12"
pbkdf2 = "0.11"

ring = "0.16"

async-trait = "0.1"

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "scram_client"

[[example]]
name = "scram_server"

[[example]]
name = "scram_server_async"

[[example]]
name = "scram_client_async"

[[example]]
name = "scram_cs"
